# This is a basic workflow to help you get started with Actions

name: My First workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'A False Optional Input'
        default: 'default value'
        type: choice
        options:
        - "default value"
        - "first option"
        - "second option"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Task: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List all file in repo
        run: |
          echo "The repo ${{ github.repository }} contains the following files:"
          tree 
    
